## 创建connor-cloud基础组件集群
## https://blog.csdn.net/RtxTitanV/article/details/106688686
version: "2"
services:
  redis:
    image: redis:5.0.0
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis/data:/data

  redis-manager:
    image: reasonduan/redis-manager:2.1.0
    container_name: redis-manager
    environment:
      - DATASOURCE_DATABASE='redis_manager'