## 常用配置
## https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties
## 服务器注册信息
spring:
  application:
    name: connor-admin-server
  profiles:
    active=: dev


feign:
  okhttp:
    enabled: true


logging:
  level:
    com.springboot.cloud: debug
    org.springframework.web: debug
    org.springframework.security: debug
  file:
    max-size: 1GB
    path: logs/


management:
  endpoints:
    web:
      exposure:
        include: '*'